package com.github.edwgiz.sample.bank.account.model;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.github.edwgiz.sample.bank.account.jooq.tables.interfaces.IAccount;
import io.swagger.v3.oas.annotations.media.Schema;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import static com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility.NONE;

/**
 * Account input REST entity.
 * Hides unnecessary fields of autogenerated Jooq interface.
 */
@JsonAutoDetect(getterVisibility = NONE, isGetterVisibility = NONE)
public class NewAccount implements IAccount {

    private String ownerName;
    private String comment;

    /**
     * Throws {@link UnsupportedOperationException}.
     */
    @Override
    public void setAccountId(final Long value) {
        throw new UnsupportedOperationException();
    }

    /**
     * Throws {@link UnsupportedOperationException}.
     */
    @Schema(hidden = true)
    @Override
    public Long getAccountId() {
        throw new UnsupportedOperationException();
    }

    /**
     * Throws {@link UnsupportedOperationException}.
     */
    @Override
    public void setCreated(final LocalDateTime value) {
        throw new UnsupportedOperationException();
    }

    /**
     * Throws {@link UnsupportedOperationException}.
     */
    @Schema(hidden = true)
    @Override
    public LocalDateTime getCreated() {
        throw new UnsupportedOperationException();
    }

    @Override
    public final void setOwnerName(final String value) {
        ownerName = value;
    }

    @JsonGetter
    @Override
    public final String getOwnerName() {
        return ownerName;
    }

    /**
     * Throws {@link UnsupportedOperationException}.
     */
    @Override
    public void setBalance(final BigDecimal value) {
        throw new UnsupportedOperationException();
    }

    /**
     * Throws {@link UnsupportedOperationException}.
     */
    @Schema(hidden = true)
    @Override
    public BigDecimal getBalance() {
        throw new UnsupportedOperationException();
    }

    /**
     * Throws {@link UnsupportedOperationException}.
     */
    @Override
    public void setBalanceLastModified(final LocalDateTime value) {
        throw new UnsupportedOperationException();
    }

    /**
     * Throws {@link UnsupportedOperationException}.
     */
    @Schema(hidden = true)
    @Override
    public LocalDateTime getBalanceLastModified() {
        throw new UnsupportedOperationException();
    }

    @Override
    public final void setComment(final String value) {
        comment = value;
    }

    @Override
    @JsonGetter
    public final String getComment() {
        return comment;
    }

    /**
     * Throws {@link UnsupportedOperationException}.
     */
    @Override
    public void from(final IAccount from) {
        throw new UnsupportedOperationException();
    }

    /**
     * Throws {@link UnsupportedOperationException}.
     */
    @Override
    public <E extends IAccount> E into(final E into) {
        throw new UnsupportedOperationException();
    }
}
