package com.github.edwgiz.sample.bank.account.model;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.github.edwgiz.sample.bank.account.jooq.tables.interfaces.IPayment;
import io.swagger.v3.oas.annotations.media.Schema;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import static com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility.NONE;

/**
 * Payment input REST entity.
 * Hides unnecessary fields of autogenerated Jooq interface.
 */
@JsonAutoDetect(getterVisibility = NONE, isGetterVisibility = NONE)
public class NewPayment implements IPayment {

    private BigDecimal amount;
    private Long withdrawalAccountId;
    private Long depositAccountId;
    private String comment;

    /**
     * Throws {@link UnsupportedOperationException}.
     */
    @Override
    public void setPaymentId(final Long value) {
        throw new UnsupportedOperationException();
    }

    /**
     * Throws {@link UnsupportedOperationException}.
     */
    @Override
    @Schema(hidden = true)
    public Long getPaymentId() {
        throw new UnsupportedOperationException();
    }

    /**
     * Throws {@link UnsupportedOperationException}.
     */
    @Override
    public void setProcessed(final LocalDateTime value) {
        throw new UnsupportedOperationException();
    }

    /**
     * Throws {@link UnsupportedOperationException}.
     */
    @Override
    @Schema(hidden = true)
    public LocalDateTime getProcessed() {
        throw new UnsupportedOperationException();
    }

    @SuppressWarnings("checkstyle:all")
    public final void setAmount(final BigDecimal amount) {
        this.amount = amount;
    }

    @JsonGetter
    @SuppressWarnings("checkstyle:MissingJavadocMethod")
    public final BigDecimal getAmount() {
        return amount;
    }

    @JsonGetter
    @SuppressWarnings("checkstyle:MissingJavadocMethod")
    public final Long getWithdrawalAccountId() {
        return withdrawalAccountId;
    }

    @SuppressWarnings("checkstyle:MissingJavadocMethod")
    public final void setWithdrawalAccountId(final Long value) {
        this.withdrawalAccountId = value;
    }

    @JsonGetter
    @SuppressWarnings("checkstyle:MissingJavadocMethod")
    public final Long getDepositAccountId() {
        return depositAccountId;
    }

    @SuppressWarnings("checkstyle:MissingJavadocMethod")
    public final void setDepositAccountId(final Long value) {
        this.depositAccountId = value;
    }

    @JsonGetter
    @SuppressWarnings("checkstyle:MissingJavadocMethod")
    public final String getComment() {
        return comment;
    }

    @SuppressWarnings("checkstyle:MissingJavadocMethod")
    public final void setComment(final String value) {
        this.comment = value;
    }

    /**
     * Throws {@link UnsupportedOperationException}.
     */
    @Override
    public void from(final IPayment from) {
        throw new UnsupportedOperationException();
    }

    /**
     * Throws {@link UnsupportedOperationException}.
     */
    @Override
    public <E extends IPayment> E into(final E into) {
        throw new UnsupportedOperationException();
    }
}
