package com.github.edwgiz.sample.bank.account.model;

import com.fasterxml.jackson.annotation.JsonGetter;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * Account input REST entity.
 * Hides unnecessary fields of autogenerated Jooq interface.
 */
public class UpdateAccount extends NewAccount {

    private Long accountId;

    @Override
    public final void setAccountId(final Long value) {
        accountId = value;
    }

    @Schema(required = true)
    @JsonGetter
    @Override
    public final Long getAccountId() {
        return accountId;
    }
}
