CREATE TABLE ACCOUNT
(
    ACCOUNT_ID            BIGINT  PRIMARY KEY  AUTO_INCREMENT NOT NULL,
    CREATED               TIMESTAMP(3)   NOT NULL,
    OWNER_NAME            VARCHAR(128)   NOT NULL,
    BALANCE               DECIMAL(16, 2) NOT NULL
        CONSTRAINT ACCOUNT__NOT_NEGATIVE_BALANCE CHECK (BALANCE >= 0),
    BALANCE_LAST_MODIFIED TIMESTAMP(3)   NOT NULL,
    COMMENT               VARCHAR(256)
);
-- below comments will be visible in swagger schema
COMMENT ON COLUMN ACCOUNT.ACCOUNT_ID IS 'Unique Identifier';
COMMENT ON COLUMN ACCOUNT.CREATED IS 'When the account was created, UTC';
COMMENT ON COLUMN ACCOUNT.OWNER_NAME IS 'Owner Name';
COMMENT ON COLUMN ACCOUNT.BALANCE IS 'Current balance';
COMMENT ON COLUMN ACCOUNT.BALANCE_LAST_MODIFIED IS 'When the balance was changed last time, UTC';
COMMENT ON COLUMN ACCOUNT.COMMENT IS 'Commentary';

INSERT INTO ACCOUNT (ACCOUNT_ID, CREATED, OWNER_NAME, BALANCE, BALANCE_LAST_MODIFIED, COMMENT)
VALUES (0, '2000-01-01 12:00:00.000', 'Bank', 1000000000, '2000-01-01 12:00:00.000', null);
INSERT INTO ACCOUNT (ACCOUNT_ID, CREATED, OWNER_NAME, BALANCE, BALANCE_LAST_MODIFIED, COMMENT)
VALUES (1, '2000-01-02 12:00:00.000', 'James Gosling', 1000000, '2000-01-02 12:00:00.000', null);
INSERT INTO ACCOUNT (ACCOUNT_ID, CREATED, OWNER_NAME, BALANCE, BALANCE_LAST_MODIFIED, COMMENT)
VALUES (2, '2000-01-03 12:00:00.000', 'John Smith', 1000, '2000-01-03 12:00:00.000', 'Demo Account');

COMMIT;


CREATE TABLE PAYMENT
(
    PAYMENT_ID            BIGINT  PRIMARY KEY  AUTO_INCREMENT NOT NULL,
    PROCESSED             TIMESTAMP(3)   NOT NULL,
    AMOUNT                DECIMAL(16, 2) NOT NULL
        CONSTRAINT PAYMENT__POSITIVE_AMOUNT CHECK ( AMOUNT > 0 ),
    WITHDRAWAL_ACCOUNT_ID BIGINT         NOT NULL
        CONSTRAINT PAYMENT__WITHDRAWAL_ACCOUNT__FK REFERENCES ACCOUNT (ACCOUNT_ID),
    DEPOSIT_ACCOUNT_ID    BIGINT         NOT NULL
        CONSTRAINT PAYMENT__DEPOSIT_ACCOUNT__FK REFERENCES ACCOUNT (ACCOUNT_ID),
    COMMENT               VARCHAR(256)
);
COMMENT ON COLUMN PAYMENT.PAYMENT_ID IS 'Unique Identifier';
COMMENT ON COLUMN PAYMENT.PROCESSED IS 'Processing date-time, UTC';
COMMENT ON COLUMN PAYMENT.AMOUNT IS 'Transferring amount';
COMMENT ON COLUMN PAYMENT.WITHDRAWAL_ACCOUNT_ID IS 'Account Identifier to withdraw funds';
COMMENT ON COLUMN PAYMENT.DEPOSIT_ACCOUNT_ID IS 'Account Identifier to deposit funds';
COMMENT ON COLUMN PAYMENT.COMMENT IS 'Commentary';


